export const surpriseMePrompts = [
  'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  'panda mad scientist mixing sparkling chemicals, digital art',
  'A macro 35mm photograph of two mice in Hawaii, they are each wearing tiny swimsuits and are carrying tiny surf boards, digital art',
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'A stained glass window depicting a hamburger and french fries',
  'A pencil and watercolor drawing of a bright city in the future with flying cars',
  'A sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'A fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  'A sea otter with a pearl earring by Johannes Vermeer',
  'An oil pastel drawing of an annoyed cat in a spaceship',
  'A painting of a fox in the style of Starry Night',
  'A bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubiks cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
  'A high-tech city of the future, where drones and hovercrafts zip around skyscrapers made of shimmering glass.',
  'A deserted space station drifting through the void, haunted by the ghosts of its former crew.',
  'A post-apocalyptic cityscape where nature has reclaimed the ruins and vines crawl up the skyscrapers',
  'An epic space battle between an armada of alien ships and a lone human vessel, fighting for the survival of Earth',
  'A stunning digital portrait of a baby animal, with ultra-detailed features and neon light accents',
  'A punk-style street art installation featuring cute kawaii characters with psychedelic designs',
  'A dreamlike world of cute baby animals with psychedelic colors and neon lights Adorable kawaii creatures living in a punk-style city, surrounded by ultra-detailed architecture',
  'A beautiful, magical forest filled with cute baby animals and dreamlike flowers',
  'An ultra-detailed portrait of a baby animal with neon light accents, showcasing its cuteness and beauty',
  'A punk-style fashion show featuring adorable models dressed in kawaii clothing and neon accessories',
  'A dreamlike underwater world filled with cute sea creatures, shimmering neon lights, and beautiful coral reefs',
  'A stunning digital art piece of a cute baby animal, with 8K resolution and ultra-detailed features',
  'A cute and cuddly plush toy collection, featuring adorable creatures with psychedelic designs',
  'A neon-lit metropolis, shrouded in darkness, where the pulsing beat of the music drives the masses into a frenzy of cybernetic hedonism',
  'A desolate wasteland, populated by the ruins of a long-forgotten civilization, where the only sound is the eerie howling of the wind and the pulsing bass of the music',
  'A sprawling, subterranean complex, filled with the sound of heavy machinery and the flickering light of neon signs, as a lone figure navigates the maze of pipes and conduits',
  'A post-apocalyptic city, overrun by gangs and scavengers, where the music serves as the only source of hope in a world gone mad',
  'A haunted mansion, abandoned for decades, where the distorted sounds of dark synth music echo through the decrepit halls and the flickering candles cast eerie shadows',
  'A cybernetic jungle, where the pulsing beats of dark synth music mix with the sounds of exotic creatures and the neon glow of bioluminescent flora',
  'A futuristic nightclub, where the music and the architecture are both equally alien and unsettling, as dancers writhe in syncopated movements under the pulsing lights',
  'A city of the past loomed in the background, illuminated only by the distant twinkle of lights. A strikingly gorgeous vampire stood before it, her body clad in shimmering silk, her hair intricately woven, and a sword clutched in her hand. The play of light and shadow on her figure, tenebrism, and chiaroscuro, brought out the colorful beauty of the scene, all captured in stunning 8K resolution through the power of Octane render and Real Engine 5. The level of detail was exquisite, almost cinematic, and the realism was as if it was captured through a camera lens',
  'A stunning depiction of Sailor Moon in a space-black suit, with multicolored hair and striking blue eyes, floating majestically in outer space aboard a spaceship. The Grisaille effect brings an otherworldly, fantastical quality to the piece, while the use of natural lighting and shadows creates a dreamy, midnight aura.',
  'A fantastical creature with a stylized form, adorned in vivid colors that seem to glow with an otherworldly aura. Every inch of its body is meticulously crafted with ultra details that make it seem almost alive. Captured in surreal photography, this magical being appears as if its stepped out of a dream. Its full body is expertly rendered in 8k resolution, showcasing the tiniest details in stunning clarity. The creatures form exudes an air of Dark Synth that adds to its enigmatic allure. Its shape is expertly crafted with Feng Shui principles in mind, imbuing it with a sense of harmony and balance. The artwork is produced using Blender software, which enhances the Grisaille style to create an intriguing contrast of light and shadow. With the use of Octane render, every curve and contour of the creature is brought to life in breathtaking detail',
  'A majestic dragon perched atop a mountain, breathing fire into the sunset sky, rendered in photorealistic detail with an 8K resolution',
  'A cinematic depiction of a heroic warrior battling a giant, terrifying monster in an epic fantasy landscape, using octane render for stunning visual effects',
  'A hyperrealistic 3D render of a sea serpent swimming in the depths of the ocean, with ultra HD textures and detailed scales',
  'A hyperrealistic 3D render of a giant squid swimming in the depths of the ocean, with ultra HD textures and detailed tentacles',
  'A hyper-realistic 3D render of a young woman with curly blonde hair and piercing blue eyes, in a full-body shot wearing an elegant black evening gown with intricate beading and lace details, with a cinematic atmosphere and Bar lighting',
  'a photorealistic portrait of a beautiful Asian woman with long dark hair and a delicate flower tiara, depicted in a 4K resolution painting with luminism techniques, inspired by the works of Alphonse Mucha and Artgerm',
  'A vibrant, magical illustration of a forest nymph with pastel colors and watercolor effects in the style of Arthur Rackham or Brian Froud. Full body shot, 8K resolution, intricate details, photorealistic rendering, and bokeh lighting',
  'A hyper-realistic digital painting of a fierce warrior queen inspired by the works of Brom or Frank Frazetta. Full-body shot with a metallic armor set, intricate details, ultra HD textures, and monochromatic color palette',
  'A stunning cover art of a space goddess in a futuristic, cyberpunk setting inspired by the works of Hajime Sorayama or Simon Stålenhag. The artwork features a centered and isometric perspective, with a 3D render and Octane render software, glowing neon lighting, and hyper-detailed character design',
  'A breathtaking illustration of a mermaid underwater in a realistic, almost photographic style inspired by the works of Greg Rutkowski or Artgerm. Full body shot with ultra HD textures, intricately detailed scales, and hyper-realistic rendering. The artwork also features Cinematic effects and bar lighting',
  'An enchanting illustration of a fairy queen in a whimsical, Art Nouveau style inspired by the works of Alphonse Mucha or Erte. The artwork features a hyperdetailed painting of the full body shot, luminism lighting, and a titanium decorative headdress. It is a hand-drawn and hand-painted artwork with intricate details and high definition',
  'A 3D hyperrealistic illustration of a mermaid swimming in the depths of the ocean, with ultra-detailed scales and intricately realistic fins, inspired by the style of artist Greg Rutkowski',
  'A portrait of a beautiful woman in a flowing gown, rendered in 3D with ultra-detailed textures and intricately realistic hair, inspired by the style of Art Nouveau artist Alphonse Mucha',
  'A hyper-realistic, ultra-detailed rendering of the monstrous Kraken, complete with intricate, detailed tentacles and a fearsome expression, taking inspiration from the artwork of H.P. Lovecraft and Guillermo del Toro',
  'A 3D hyper realistic digital illustration of a sci-fi spaceship, approaching perfection in its design and details. The spaceship is rendered in a comic book style, with sharp focus and smooth coloring that make the intricate details pop. The centered composition and dynamic positioning of the spaceship make it a standout on artstation, inspired by the work of Carne Griffiths and Wadim Kashin. This highly detailed concept art is perfect for showcasing the artists skills in creating hyper realistic and detailed sci-fi illustrations',
  'A sci-fi spaceport bustling with activity, depicted in a highly detailed digital illustration with a comic book style, rendered in ultra HD and featuring a diverse cast of characters. Art by Simon Stålenhag and Alex Ross',
  'A mythical forest filled with magical creatures, captured in a stunningly realistic digital illustration with a sharp focus and intricate details. Art by Ian McQue and Keith Thompson',
  'A cyberpunk metropolis teeming with neon lights and towering skyscrapers, portrayed in a dynamic digital illustration with a cinematic flair, featuring hyperrealistic textures and materials. Art by Kekai Kotaki and Maciej Kuciara',
  'A post-apocalyptic wasteland filled with ruins and danger, depicted in a smooth and polished digital illustration with an isometric view, showcasing intricate details and a desolate atmosphere. Art by Wojtek Fus and Marko Djurdjevic',
  'Design an otherworldly creature that could inhabit a planet with extreme conditions',
  'Create a futuristic cityscape that reflects the culture and values of its inhabitants',
  'Design a futuristic cityscape with towering skyscrapers and neon-lit streets, inspired by the Art Deco style and featuring a central park with a sinister secret',
  'Create a hyper-realistic portrait of a mythical creature, such as a dragon or a unicorn, rendered in the style of a Baroque oil painting',
  'Imagine a post-apocalyptic world in which nature has taken over, and design a vehicle that can traverse the overgrown landscape while avoiding dangerous mutant creatures',
  'Create a landscape that is both beautiful and terrifying, with a dark synth soundtrack and a chiaroscuro lighting scheme, inspired by the works of H.R. Giger',
  'Design a high-tech suit of armor for a sci-fi hero, incorporating elements of biomechanics, nanotechnology, and futuristic materials',
  'Create a stunning portrait of a powerful sorceress, surrounded by arcane symbols and glowing magical energy, inspired by the works of Frank Frazetta',
  'Imagine a steampunk-inspired world in which clockwork robots roam the streets, and design a dirigible that can traverse the skies while avoiding hazards such as sky pirates and dangerous storms',
  'Create a surreal landscape that defies the laws of physics, featuring impossible structures and strange, otherworldly creatures',
  'Design a vehicle for exploring the deep sea, inspired by the works of Jules Verne and featuring advanced technologies such as underwater drones and submersible habitats',
  'Create a dystopian landscape that is both post-apocalyptic and awe-inspiring, featuring imposing structures and crumbling ruins, inspired by the works of George Miller',
  'Imagine a world in which humans have evolved into advanced cyborgs, and design a powerful exosuit that can enhance their abilities and protect them from danger',
  'Create a beautiful and intricate mandala, featuring intricate patterns and vibrant colors inspired by the works of Alex Grey',
  'Design a high-tech laboratory for a mad scientist, incorporating advanced equipment such as gene sequencers, quantum computers, and particle accelerators',
  'Create a landscape inspired by the works of H.P. Lovecraft, featuring ancient ruins, malevolent deities, and strange cosmic entities',
  'Imagine a world in which humans have colonized other planets, and design a terraforming vehicle that can transform barren wastelands into habitable environments',
  'Create a stunning portrait of a warrior queen, adorned with intricate armor and wielding a powerful weapon, inspired by the works of Brom',
  'Design a spacecraft for a crew of interstellar explorers, featuring advanced propulsion systems, cryogenic chambers, and a state-of-the-art AI assistant',
  'Create a surreal and dreamlike landscape, featuring floating islands, twisting vines, and strange creatures with glowing eyes',
  'Imagine a world in which technology has advanced to the point of immortality, and design a towering citadel that serves as a sanctuary for the elite',
  'Create a portrait of a cybernetic samurai, wielding a deadly katana and featuring advanced cybernetic enhancements such as enhanced strength and reflexes',

];
